In [2]:
import pandas as pd, numpy as np

area_data = pd.read_csv("./area_data.csv")
area_data.dropna(inplace=True)
area_data = area_data[area_data["link"].apply(lambda x: ".csv" in x)]
area_data["area"] = area_data["area"].apply(lambda x: x.replace(" (ACT)", ""))

for i in area_data.index:
    data = pd.read_csv(
        area_data.at[i, "link"]
    )
    for j in data.index:
        area_data.at[i, data.at[j, "Description"]] = data.loc[j].dropna()[-1]
    area_data.at[i, "past_population"] = data.at[0, "2015"]

area_data.to_csv("./sa2_data.csv", index=False)

c:\users\mannheimm6l\appdata\local\programs\python\python39\lib\site-packages\pandas\core\indexing.py:1684: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  self.obj[key] = infer_fill_value(value)

In [42]:
data = area_data.loc[:, "code":"area"]
data["population"] = area_data[area_data.columns[3]]
data["population density"] = area_data[area_data.columns[4]]
data["median age"] = area_data[area_data.columns[9]]
data["children under 15"] = area_data[area_data.columns[102:105]].sum(axis=1) / 100
data["people over 64"] = area_data[area_data.columns[115:120]].sum(axis=1) / 100
data["fertility rate"] = area_data[area_data.columns[121]] / 100
data["Indigenous"] = area_data[area_data.columns[129]] / 100
data["religious"] = 1 - (area_data[area_data.columns[147]] / 100)
data["born overseas"] = area_data[area_data.columns[139]] / 100
data["born in Oceania"] = area_data[area_data.columns[130]] / 100
data["born in north-west Europe"] = area_data[area_data.columns[131]] / 100
data["born in southern & eastern Europe"] = area_data[area_data.columns[132]] / 100
data["born in north Africa & Middle East"] = area_data[area_data.columns[133]] / 100
data["born in south-east Asia"] = area_data[area_data.columns[134]] / 100
data["born in north-east Asia"] = area_data[area_data.columns[135]] / 100
data["born in southern & central Asia"] = area_data[area_data.columns[136]] / 100
data["born in Americas"] = area_data[area_data.columns[137]] / 100
data["born in sub-Saharan Africa"] = area_data[area_data.columns[138]] / 100
data["median house price"] = area_data[area_data.columns[248]]
data["median income"] = area_data[area_data.columns[312]]
data["low income (bottom quartile)"] = area_data[area_data.columns[322]] / 100
data["high income (top quartile)"] = area_data[area_data.columns[325]] / 100
data["postgraduates"] = area_data[area_data.columns[391]] / 100
data["university graduates"] = area_data[area_data.columns[391:394]].sum(axis=1) / 100
data["jobs: managers"] = area_data[area_data.columns[421]] / 100
data["jobs: professionals"] = area_data[area_data.columns[422]] / 100
data["jobs: technicians & trades"] = area_data[area_data.columns[423]] / 100
data["jobs: community work"] = area_data[area_data.columns[424]] / 100
data["jobs: clerical"] = area_data[area_data.columns[425]] / 100
data["jobs: sales"] = area_data[area_data.columns[426]] / 100
data["jobs: machinery & drivers"] = area_data[area_data.columns[427]] / 100
data["jobs: labourers"] = area_data[area_data.columns[428]] / 100
data["home owners (outright)"] = area_data[area_data.columns[505]] / 100
data["home owners (mortgage)"] = area_data[area_data.columns[506]] / 100
data["renters"] = area_data[area_data.columns[507]] / 100
data["detached houses"] = area_data[area_data.columns[500]] / area_data[area_data.columns[504]]
data["artificial surfaces"] = area_data[area_data.columns[601]] / area_data[area_data.columns[583]]
data.to_csv("./data.csv", index=False)
geo = pd.read_csv("data_geocoded.csv")
data_clean = data.set_index("code").join(geo[["code", "lng", "lat"]].set_index("code"))
data_clean = data_clean[data_clean["population"] > 149]
data_clean.to_csv("./data_clean.csv")

In [41]:
districts = ["Belconnen", "other", "other", "Gungahlin", "North Canberra", "South Canberra", "Tuggeranong", "Weston Creek", "Woden", "Molonglo", "other"]
for code in data_clean.index:
    data_clean.at[code, "district"] = districts[int(str(code)[3:5]) - 1]
data_clean

,area,population,population density,median age,children under 15,people over 64,fertility rate,Indigenous,religious,born overseas,...,jobs: machinery & drivers,jobs: labourers,home owners (outright),home owners (mortgage),renters,detached houses,artificial surfaces,lng,lat,district
code,,,,,,,,,,,,,,,,,,,,,
801011001,Aranda,2501.0,1600.0,42.8,0.212,0.188,0.0195,0.007,0.570,0.241,...,0.010,0.084,0.444,0.344,0.185,0.882353,NaN,149.080410,-35.258158,NaN
801011002,Belconnen,7634.0,1724.8,31.0,0.091,0.086,0.0101,0.012,0.571,0.462,...,0.020,0.084,0.094,0.198,0.680,0.008715,0.013514,149.067625,-35.235652,NaN
801011003,Bruce,7679.0,1324.5,28.0,0.111,0.093,0.0101,0.008,0.558,0.384,...,0.017,0.068,0.180,0.217,0.569,0.187089,0.005217,149.090835,-35.244040,NaN
801011004,Charnwood,2860.0,1541.0,35.7,0.222,0.133,0.0236,0.031,0.761,0.194,...,0.010,0.166,0.216,0.441,0.315,0.884788,0.024540,149.034130,-35.200177,NaN
801011005,Cook,2810.0,1775.0,43.5,0.184,0.201,0.0190,0.013,0.581,0.251,...,0.008,0.065,0.382,0.351,0.245,0.585616,0.019231,149.066397,-35.260074,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801101135,Coombs,3806.0,1642.0,31.5,0.266,0.037,0.0235,0.014,0.795,0.352,...,0.017,0.043,0.106,0.738,0.130,0.531707,0.021008,149.042443,-35.316748,NaN
801101136,Denman Prospect,963.0,203.0,30.0,0.258,0.023,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.024821,-35.296408,NaN
801101139,Wright,3786.0,2977.4,32.6,0.200,0.042,0.0105,0.005,0.752,0.293,...,0.012,0.029,0.069,0.698,0.211,0.342831,0.048000,149.033601,-35.319267,NaN
801111140,ACT - South West,590.0,1.4,34.1,0.248,0.066,NaN,0.007,0.606,0.117,...,0.025,0.085,0.170,0.614,0.190,0.980000,NaN,148.960693,-35.390998,NaN
code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,other